### PR TITLE
Fix escaping of ' and \ in pattern rule

### PR DESCRIPTION
**Pull request by tomp4l**
Adds slashes to ' and \ to escape php single quoted string.

### CODE REVIEW

**Comment by mikaelcom** [comment]
Hi, thanks for your contribution!

Could you create an issue with the cause that encouraged you to fix the pattern rule?

In addition, did you notice your fix altered the patterns as it add an additional `\` which seems unnecessary:
```php
preg_match('/[_a-zA-Z0-9\-\+\.]+@[a-zA-Z0-9\-]+(\.[a-zA-Z0-9\-]+)*(\.[a-zA-Z]+)/', $email)
```
becomes
```php
preg_match('/[_a-zA-Z0-9\\-\\+\\.]+@[a-zA-Z0-9\\-]+(\\.[a-zA-Z0-9\\-]+)*(\\.[a-zA-Z]+)/', $email)
```
The first version should be kept as it is.

**Comment by tomp4l** [comment]
Sure, I'll create an issue now.

In terms of the strings they parse in PHP to exactly the same thing:

```
var_dump('/[_a-zA-Z0-9\-\+\.]+@[a-zA-Z0-9\-]+(\.[a-zA-Z0-9\-]+)*(\.[a-zA-Z]+)/' === '/[_a-zA-Z0-9\\-\\+\\.]+@[a-zA-Z0-9\\-]+(\\.[a-zA-Z0-9\\-]+)*(\\.[a-zA-Z]+)/');
// bool(true)
```
Without escaping the `\` you get issues in the test case I added:

```
$value = '\\\\' // converts to \\ after php single quote escaping
// no escaping:
preg_match('/\\/', $foo) //preg_match(): No ending delimiter '/' found in Command line code on line 1
//with escaping 
preg_match('/\\\\/', $foo)  // equivalent to /\\/
```

**Comment by mikaelcom** [comment]
Thanks for the issue and the explanation!

Could you ensure unit tests pass as they are broken https://travis-ci.org/WsdlToPhp/PackageGenerator/builds/270389148. You mainly have to fix the unit test resources which contain pattern rules

**Comment by tomp4l** [comment]
Thanks for the feedback, am still getting failures on `WsdlToPhp\PackageGenerator\Tests\File\StructTest::testWriteDeliveryServiceStructExpiryDate` for some reason, seems like some sort of encoding issue but I think it will pass travis.

**Comment by mikaelcom** [comment]
thx, I'll integrate it soon, please be patient 😉

**Pull request merged**
